### ISSUE TITLE
Gather information about how to send mails from code with Ruby on Rails. Document what you found out.

### ISSUE THREAD

**Issue by antoniusnaumann** [hpi-swt2/contacts-portal#106]
Alternative: Find out how to connect to openID

**Comment by SanJSp** [comment]
## Email verification using Devise & Gmails SMTP Service

Since Devise is already integrated in the project, the basic functionalities for email support are already there. We just have to append/ edit these basics (see the tutorial below for details). Furthermore, we need to create an email account. In the example, gmail is being used, but we can discuss, wether there are other solutions. With the straight-forward tutorial, which is already modified according to our project, there shouldn't be many difficulties. 

[Tutorial](https://www.bogotobogo.com/RubyOnRails/RubyOnRails_Devise_Authentication_Sending_Confirmation_Email.php)

You can take a look at the selected steps relevant to us or easier: follow the tutorial above for a brain free coding session!
![image alt](https://media.giphy.com/media/BBkKEBJkmFbTG/giphy.gif)

We need to do the following:

- Configure Devise
    - in config/environments/development.rb
     
```      config.action_mailer.perform_deliveries = true
  config.action_mailer.raise_delivery_errors = true
  config.action_mailer.default_url_options = { host: ENV['MAIL_HOST'] }
  config.action_mailer.delivery_method = :smtp
  config.action_mailer.smtp_settings = {
    user_name:      tbd,
    password:       tbd,
    domain:         localhost:3000,
    address:       'smtp.gmail.com',
    port:          '587',
    authentication: :plain,
    enable_starttls_auto: true
  }
  
```
- 
    -  default url options already set
- Add Notices and alerts to application.html.erb
    - app/views/application.html.erb above <%=yield %>
    `<p class="notice"><%= notice %></p><p class="alert"><%= alert %></p>
`
    - not sure whether this is relevant for us
- edit user model
    - make it look like this

```
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, 
         :confirmable
end
```
- migrate
    - in db/migrations/2020..._devise_create_users.rb uncomment following lines
```
## Confirmable
t.string   :confirmation_token
t.datetime :confirmed_at
t.datetime :confirmation_sent_at
t.string   :unconfirmed_email # Only if using reconfirmable 
## Lockable
t.integer  :failed_attempts, default: 0, null: false # Only if lock strategy is :failed_attempts
t.string   :unlock_token # Only if unlock strategy is :email or :both
t.datetime :locked_at
```

- rake db:migrate
    - `rake db:migrate -- add_index(:users, :reset_password_token, {:unique=>true})
`
    - migrate! 
![asd](https://media.giphy.com/media/YFkpsHWCsNUUo/giphy.gif)
- add links on page
    - Havent received confirmation mail?
    - ..
- Configure device mailer
- add user views

## OpenId integration
Christoph Mathies recommended to take a look at the Github repo below. We also found a possibility to include openID using devise.

[Github Repo by Christoph](https://github.com/m0n9oose/omniauth_openid_connect)
alternatively use [this devise integration](https://www.rubydoc.info/gems/devise_openid_authenticatable/1.3.0)

This one is a bit more tricky. But dont worry, you'll make it!
![image alt](https://media.giphy.com/media/DgLsbUL7SG3kI/giphy.gif)
