### ISSUE TITLE
Database defect after #54

### ISSUE THREAD

**Issue by LinqLover** [hpi-swt2/contacts-portal#115]
@felixauringer reported that the database cannot be recreated after #54 has been merged.

Tasks:
- [ ] reproduce the problem
- [ ] find a solution to it

**Comment by felixauringer** [comment]
I can reproduce my error with:

- rollback your migration with `rails db:migrate:down VERSION=20201211160500`
- migrate the database again with `rails db:migrate`

I then get the error

```text
== 20201211160500 AddCreatorUserToNotes: migrating ============================
-- add_reference(:notes, :creator_user, {:null=>false, :default=>"", :foreign_key=>{:to_table=>:users}})
rails aborted!
StandardError: An error has occurred, this and all later migrations canceled:

SQLite3::SQLException: Cannot add a NOT NULL column with default value NULL
/home/vagrant/hpi-swt2/db/migrate/20201211160500_add_creator_user_to_notes.rb:4:in `change'
bin/rails:4:in `<main>'

Caused by:
ActiveRecord::StatementInvalid: SQLite3::SQLException: Cannot add a NOT NULL column with default value NULL
/home/vagrant/hpi-swt2/db/migrate/20201211160500_add_creator_user_to_notes.rb:4:in `change'
bin/rails:4:in `<main>'

Caused by:
SQLite3::SQLException: Cannot add a NOT NULL column with default value NULL
/home/vagrant/hpi-swt2/db/migrate/20201211160500_add_creator_user_to_notes.rb:4:in `change'
bin/rails:4:in `<main>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
```

The problem seems to be fixable by executing `rails db:reset` while the current `schema.rb` from `dev` is checked out.

If the migration was successful there does not seem to be any error after that (except you roll back again). Therefore it may be best to just leave the migration as it is because there do not seem to be many other people than me that experienced this problem.

**Comment by LinqLover** [comment]
Thanks for the explanation!
