### ISSUE TITLE
Navigation in the web-app

### ISSUE THREAD

**Issue by inadicis** [hpi-swt2/contacts-portal#146]
# Description
As a user I want to have an footer and a header to be able to navigate between the different pages of the web-app.  
In the footer there should be 
 - Dashboard
 - Chat
 - Contacts
 - History
 - Settings button

In the Header there should be 
- the App-Title
- a Search
- a Notification button  

# Dependencies

# Conditions of satisfaction
See wireframe at #138

**Comment by rheaSPK** [comment]
@inadicis Because of the header and footer, the dashboard website isn't compatible with the new design, there has to be a ticket for reworking it's design. Also, some menu points, that were linked in the old Navigation bar aren't included in the new one. Is this a problem? I could easily add a drop down menu, to get the old menu points till everything is added to the new menu bar.

**Comment by rheaSPK** [comment]
@inadicis The wireframes that are used throughout the tickets have a different header and footer design. I strictly implemented #138, just FYI, that there isn't any miscommunication
