### ISSUE TITLE
[User Story] Import From CardDav

### ISSUE THREAD

**Issue by florian-papsdorf** [hpi-swt2/contacts-portal#71]
# Description
As a user I want to import contacts from a CardDav server because many services are based on this protocol.

# Conditions of satisfaction
- [ ] the import works for two of following services Apple, Gmail, NextCloud/OwnCloud

**Comment by LinqLover** [comment]
> - <input type="checkbox" disabled /> the import works for two of following services Apple, Gmail, NextCloud/OwnCloud

Please specify more in detail: What particular information should be imported? Why do you differentiate between these services if they all follow the same standard? Or do you expect some click-to-go solutions (similar to "Login with Google") instead of manually exporting your contacts from the source platform? The former, I guess, would be much more complex. :-)

**Edit:** This also needs to be evaluated.

**Comment by LinqLover** [comment]
Not yet prioritized
