### ISSUE TITLE
Contacts are bidirectional

### ISSUE THREAD

**Issue by antoniusnaumann** [hpi-swt2/contacts-portal#84]
# Description
As a user, when i accepted the request of another user, i want him to be in my contact list

# Conditions of satisfaction
- [ ] when someone accepts a request, both user should have each other in their contacts

**Comment by Paula-Kli** [comment]
we think mutuality is good

**Comment by Paula-Kli** [comment]
is mutiality able to achive through the change of the model?
does not seems so [here](https://medium.com/@miss.leslie.hsu/001-mutual-friendships-on-your-app-in-4-easy-steps-55cb27622585) since they are creating two associations in both directions in Step 4
On first sight looks like [they](https://smartfunnycool.com/friendships-in-activerecord/) have two entries in the database for friendships too

**Comment by felixauringer** [comment]
> is mutiality able to achive through the change of the model?

It is possible (see for example [here](https://stackoverflow.com/a/37244392/7804726) but I'm not sure whether this is the best way to do it.

> does not seems so [here](https://medium.com/@miss.leslie.hsu/001-mutual-friendships-on-your-app-in-4-easy-steps-55cb27622585) since they are creating two associations in both directions in Step 4

I found this [article](http://jacksenechal.com/2011/01/03/bi-directional-relationships-in-rails.html) that shows how to achieve bi-directional relationships with active record callbacks. I would prefer such a solution over a custom method (`self.create_reciprocal_for_ids`) that you have to use because the relationship would not be bi-directional if somebody (e.g. a new developer) accidentally uses the default active record methods.

> On first sight looks like [they](https://smartfunnycool.com/friendships-in-activerecord/) have two entries in the database for friendships too

Seems like this is the best or at least the fastest way. And ids are small so this solution has no big disadvantages that I can think of.

**Comment by Paula-Kli** [comment]
have a look at hooks for after create and after destroy
